### ISSUE TITLE
Building from source

### ISSUE THREAD

**Issue by yochananmarqos** [sonnyp/Tangram#86]
**Tangram version**

1.2.0.r30.gf8f5b02

**Linux distribution**

Manjaro

**Desktop environment**

GNOME 3.36.5 X11

----

I tried building from the latest commit a couple different ways. Using just Meson, it didn't work out so well:

```
  arch-meson . build
  meson compile -C build
```

```
tangram/src/meson.build:4:0: ERROR: Resource "main.js" listed in "src/re.sonny.Tangram.src.gresource.xml" was not found. If this is a generated file, pass the target that generates it to gnome.compile_resources() using the "dependencies" keyword argument.
```

I saw that Node modules were used, so tried the following first, but that didn't work out so well, either:

```
  npm install --cache "$srcdir/npm-cache"
  ./node_modules/.bin/rollup -c
```

```
> husky@4.2.5 install /home/yochanan/Documents/pkgbuilds/tangram-git/src/tangram/node_modules/husky
> node husky install

husky > Setting up git hooks
husky > Done

> husky@4.2.5 postinstall /home/yochanan/Documents/pkgbuilds/tangram-git/src/tangram/node_modules/husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 223 packages from 122 contributors and audited 224 packages in 4.971s

25 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


src/index.js → src/main.js...
[!] Error: Could not resolve '../troll/util' from src/webapp/webapp.js
Error: Could not resolve '../troll/util' from src/webapp/webapp.js
    at error (/home/yochanan/Documents/pkgbuilds/tangram-git/src/tangram/node_modules/rollup/dist/shared/rollup.js:5171:30)
    at ModuleLoader.handleResolveId (/home/yochanan/Documents/pkgbuilds/tangram-git/src/tangram/node_modules/rollup/dist/shared/rollup.js:17865:24)
    at /home/yochanan/Documents/pkgbuilds/tangram-git/src/tangram/node_modules/rollup/dist/shared/rollup.js:17857:22
    at async Promise.all (index 0)
    at async ModuleLoader.fetchStaticDependencies (/home/yochanan/Documents/pkgbuilds/tangram-git/src/tangram/node_modules/rollup/dist/shared/rollup.js:17855:34)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchModule (/home/yochanan/Documents/pkgbuilds/tangram-git/src/tangram/node_modules/rollup/dist/shared/rollup.js:17832:9)
    at async Promise.all (index 4)
    at async ModuleLoader.fetchStaticDependencies (/home/yochanan/Documents/pkgbuilds/tangram-git/src/tangram/node_modules/rollup/dist/shared/rollup.js:17855:34)
    at async Promise.all (index 0)
```

**Comment by sonnyp** [comment]
You need to clone recursively - it's in the doc.

`git clone --recursive git://github.com/sonnyp/Tangram.git`

or

```sh
git clone git://github.com/sonnyp/Tangram.git
cd Tangram
git submodule init
git submodule update
```

I made it more explicit https://github.com/sonnyp/Tangram/commit/ea52d8ec942c5672ea8e28ccd44ce1b61478138b

**Comment by yochananmarqos** [comment]
Ah, thanks.
